# Generated by Django 5.0.6 on 2024-05-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default='2024-05-21'),
            preserve_default=False,
        ),
    ]
